<?php

declare(strict_types=1);

namespace DocExtensions\SyncLanguage\Generation;

use DocExtensions\SyncLanguage\Repository\Paths;
use DocExtensions\SyncLanguage\SyncException;

final readonly class XmlText
{
    public static function banner(?string $sourceRelative): string
    {
        $from = $sourceRelative !== null
            ? ' from doc-en ' . $sourceRelative
            : '';

        return sprintf(
            "<!-- Generated by %s%s\n     DO NOT EDIT: change %s and run the script. -->",
            Paths::SCRIPT,
            $from,
            Paths::MANIFEST,
        );
    }

    public static function firstMatch(string $pattern, string $subject, string $what): string
    {
        if (!preg_match($pattern, $subject, $matches)) {
            throw new SyncException('no match for ' . $what);
        }

        return $matches[1];
    }

    public static function extractBlock(string $source, string $tagPattern, int $indent, string $what): string
    {
        if (!preg_match('/^( *)<(' . $tagPattern . ')\b.*?^ *<\/\2>/ms', $source, $m)) {
            throw new SyncException(sprintf('no <%s> block found for %s', $tagPattern, $what));
        }

        $fixed = preg_replace('/^ *(<\/' . $m[2] . '>)$/m', $m[1] . '$1', $m[0]);

        return self::reindent($fixed, strlen($m[1]), $indent);
    }

    public static function reindent(string $block, int $from, int $to): string
    {
        $lines = explode("\n", $block);
        foreach ($lines as &$line) {
            $line = rtrim($line);
            if ($line === '') {
                continue;
            }

            $line = $to >= $from
                ? str_repeat(' ', $to - $from) . $line
                : substr($line, $from - $to);
        }

        return implode("\n", $lines);
    }

    public static function wrapText(string $text, int $indent): string
    {
        $pad = str_repeat(' ', $indent);
        $lines = [];
        $current = '';
        foreach (explode(' ', $text) as $word) {
            if ($current !== '' && strlen($pad . $current . ' ' . $word) > 78) {
                $lines[] = $current;
                $current = $word;
            } else {
                $current = $current === '' ? $word : $current . ' ' . $word;
            }
        }

        $lines[] = $current;

        return implode("\n" . $pad, $lines);
    }

    /** A copied block may only link to its own property list; nothing else would resolve here. */
    public static function assertNoForeignReferences(string $xml, string $allowedLinkendPrefix, string $what): void
    {
        if (preg_match_all('/linkend="([^"]+)"/', $xml, $m)) {
            foreach ($m[1] as $linkend) {
                if ($allowedLinkendPrefix === '' || !str_starts_with($linkend, $allowedLinkendPrefix)) {
                    throw new SyncException(sprintf('%s: copied block links to "%s", which does not exist in this manual', $what, $linkend));
                }
            }
        }

        if (str_contains($xml, 'xlink:')) {
            throw new SyncException($what . ': copied block contains an xlink attribute');
        }

        if (str_contains($xml, 'xml:id=')) {
            throw new SyncException($what . ': copied block contains an xml:id (would be duplicated when included)');
        }
    }

    /** Every xi:include in a copied synopsis must point at a class that the manifest mirrors. */
    public static function assertKnownXPointers(string $xml, array $classIds, string $what): void
    {
        if (!preg_match_all("/id\\('([^']+)'\\)/", $xml, $matches)) {
            return;
        }

        foreach (array_unique($matches[1]) as $target) {
            $id = preg_replace('/^class\./', '', $target);
            if ($id === $target || !isset($classIds[$id])) {
                throw new SyncException(sprintf('%s: synopsis includes members from "%s", add that class to %s first', $what, $target, Paths::MANIFEST));
            }
        }
    }
}
